package cc.arccore.diagnostics.leak.model

enum class LeakType {
    CLASSLOADER_LEAK,
    STALE_LISTENER,
    STALE_COMMAND,
    STALE_SERVICE,
    STALE_SINGLETON,
    ORPHAN_EXECUTOR,
    ORPHAN_COROUTINE,
    ORPHAN_SCHEDULER_TASK,
    STALE_CACHE,
    DANGLING_REGISTRY_ENTRY,
    INVALID_LIFECYCLE_STATE
}
